version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend/Dockerfile  # Path to your Flask backend Dockerfile
    container_name: backend
    ports:
      - "5000:5555"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb
    depends_on:
      - mongodb
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend/Dockerfile-prod  # Path to your React frontend Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_HOST_API_KEY="/api"
    ports:
      - "8314:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data:
