version: '3.7'

networks:
  subsidia-network:
    external: true
    driver: overlay

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /mnt/mongodb:/data/db
    networks:
      - subsidia-network

  backend:
    image: backend:0.0.1
    ports:
      - "8315:5555"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == manager]
    networks:
      - subsidia-network

  frontend:
    image: frontend:0.0.1
    environment:
      - REACT_APP_HOST_API_KEY="https://subsidia.page/api"
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "8314:80"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]